# Generated by Django 2.2.5 on 2019-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20191003_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='rozmiar',
            field=models.CharField(choices=[('L', 'Duża'), ('M', 'Średnia'), ('S', 'Mała')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='jarski',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarianina', verbose_name='jarski?'),
        ),
    ]
